version: "3.7"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "63306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress